version: "3"

networks:
  app-tier:
    driver: bridge

services:
  web:
    build: .
    container_name: app
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3001:3000
      - 5555:5555
    networks:
      - app-tier
  db:
    build: ./db
    container_name: db
    restart: always
    ports:
      - 5431:5432
    networks:
      - app-tier
